# Generated by Django 5.2.4 on 2025-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productvariant_options_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('cart', 'Cart'), ('buynow', 'Buy Now')], default='cart', max_length=10),
        ),
    ]
