# Generated by Django 5.2.4 on 2025-07-28 06:15

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=api.models.AlphaNumericFieldfive(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
