# Generated by Django 5.2.4 on 2025-08-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='type_of_address',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], default='home', max_length=20),
        ),
    ]
