# Generated by Django 5.2.4 on 2025-08-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productsize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['variant_value']},
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='additional_info',
            new_name='size',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant_value')},
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_type',
        ),
    ]
