# Generated by Django 5.2.4 on 2025-08-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varient_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
