# Generated by Django 5.2.4 on 2025-08-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product', 'variant', 'varient_size')},
        ),
    ]
